# python_submission
"""
WRITE PYTHONIC CODE TO CREATE A FUNCTION NAMED MOVE RECTANGLE() THAT TAKES AN OBJECT OF RECTANGLE CLASS AND TWO NUMBERS NAMED DX AND DY. 
IT SHOULD CHANGE THE LOCATION OF THE RECTANGLE BY ADDING DX TO THE X COORDINATE OF CORNER AND ADDING DY TO THE Y COORDINATE OF CORNER AND ADDING DY TO THE Y COORDINATE OF CORNER.
""" 

class Point(object):
 
class Rectangle(object):
